image: alpine:latest

default:
  tags:
    - staging

stages:
  - deploy

deploy_to_staging:
  stage: deploy
  before_script:
    - apk update && apk add --no-cache openssh-client
    - eval $(ssh-agent -s)
    - chmod 600 $SSH_PRIVATE_KEY
    - ssh-add $SSH_PRIVATE_KEY
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -H $VM_IPADDRESS >> ~/.ssh/known_hosts

  script:
    - ssh -v $SSH_USER@$VM_IPADDRESS "cd /home/ubuntu/syncoss-tr415-frontend/ && ./deploy.sh"

  only:
    - staging
