const SUBSCRIBER_EVENTS = {
  ADD_TO_WISHLIST: 'ADD_TO_WISHLIST',
  REMOVE_FROM_WISHLIST: 'REMOVE_FROM_WISHLIST',
  ADD_TO_CART: 'ADD_TO_CART',
  REMOVE_FROM_CART: 'REMOVE_FROM_CART',
  CREATE_ORDER: 'CREATE_ORDER',
}

module.exports = {
  SUBSCRIBER_EVENTS,
}
